In [3]:
import pandas as pd
import json

In [4]:
filename = 'data/20260105_8278074507_MiFitness_hlth_center_aggregated_fitness_data.csv'
df = pd.read_csv(filename)

In [5]:
print(list(df.columns))

['Uid', 'Sid', 'Tag', 'Key', 'Time', 'Value', 'UpdateTime']

In [6]:
pd.get_option("display.max_colwidth")
pd.set_option("display.max_colwidth", None)

Access one specific(epoch = 1767484800) `sleep` data

In [21]:
sleep_data_1767484800 = df.Value[(df.Key == 'sleep') & (df.Time == 1767484800) & (df.Tag == 'daily_report')]
sleep_data_1767484800

1038    {"total_turn_over":0,"sleep_deep_duration":114,"avg_spo2":98,"day_sleep_evaluation":0,"avg_hr":49,"total_snore_disturb":0,"total_duration":441,"awake_count":2,"total_body_move":0,"sleep_rem_duration":102,"breath_quality":0,"sleep_awake_duration":6,"max_spo2":99,"total_snore":0,"sleep_light_duration":225,"sleep_nap_duration":0,"segment_details":[{"avg_hr":49,"bedtime":1767482880,"max_spo2":99,"min_hr":41,"sleep_rem_duration":102,"timezone":4,"sleep_light_duration":225,"sleep_deep_duration":114,"sleep_awake_duration":6,"duration":441,"max_hr":80,"awake_count":2,"avg_spo2":98,"min_spo2":95,"wake_up_time":1767509700}],"max_hr":80,"min_spo2":95,"sleep_trace_duration":0,"min_hr":41,"long_sleep_evaluation":3,"sleep_algorithm_version":0,"sleep_score":80,"total_long_duration":441,"sleep_manually_duration":0}
Name: Value, dtype: object

Parse JSON of one specific(epoch = 1767484800) `sleep` data into a new DF

In [ ]:

# TODO explode()?
sleep_data_1767484800_json = json.loads('[' + ','.join(sleep_data_1767484800) + ']')
print(sleep_data_1767484800_json)
sleep_data_1767484800_df = pd.json_normalize(data=sleep_data_1767484800_json, max_level=2)
sleep_data_1767484800_df

[{'total_turn_over': 0, 'sleep_deep_duration': 114, 'avg_spo2': 98, 'day_sleep_evaluation': 0, 'avg_hr': 49, 'total_snore_disturb': 0, 'total_duration': 441, 'awake_count': 2, 'total_body_move': 0, 'sleep_rem_duration': 102, 'breath_quality': 0, 'sleep_awake_duration': 6, 'max_spo2': 99, 'total_snore': 0, 'sleep_light_duration': 225, 'sleep_nap_duration': 0, 'segment_details': [{'avg_hr': 49, 'bedtime': 1767482880, 'max_spo2': 99, 'min_hr': 41, 'sleep_rem_duration': 102, 'timezone': 4, 'sleep_light_duration': 225, 'sleep_deep_duration': 114, 'sleep_awake_duration': 6, 'duration': 441, 'max_hr': 80, 'awake_count': 2, 'avg_spo2': 98, 'min_spo2': 95, 'wake_up_time': 1767509700}], 'max_hr': 80, 'min_spo2': 95, 'sleep_trace_duration': 0, 'min_hr': 41, 'long_sleep_evaluation': 3, 'sleep_algorithm_version': 0, 'sleep_score': 80, 'total_long_duration': 441, 'sleep_manually_duration': 0}]

,total_turn_over,sleep_deep_duration,avg_spo2,day_sleep_evaluation,avg_hr,total_snore_disturb,total_duration,awake_count,total_body_move,sleep_rem_duration,...,segment_details,max_hr,min_spo2,sleep_trace_duration,min_hr,long_sleep_evaluation,sleep_algorithm_version,sleep_score,total_long_duration,sleep_manually_duration
0,0,114,98,0,49,0,441,2,0,102,...,"[{'avg_hr': 49, 'bedtime': 1767482880, 'max_spo2': 99, 'min_hr': 41, 'sleep_rem_duration': 102, 'timezone': 4, 'sleep_light_duration': 225, 'sleep_deep_duration': 114, 'sleep_awake_duration': 6, 'duration': 441, 'max_hr': 80, 'awake_count': 2, 'avg_spo2': 98, 'min_spo2': 95, 'wake_up_time': 1767509700}]",80,95,0,41,3,0,80,441,0

Access `segment_details` data
Turn into a new df
Merge two df

In [52]:
print(sleep_data_1767484800_df['segment_details'])
sleep_data_1767484800_segment_details_df = pd.json_normalize(sleep_data_1767484800_df.explode('segment_details')['segment_details'])
sleep_data_1767484800_segment_details_df

0    [{'avg_hr': 49, 'bedtime': 1767482880, 'max_spo2': 99, 'min_hr': 41, 'sleep_rem_duration': 102, 'timezone': 4, 'sleep_light_duration': 225, 'sleep_deep_duration': 114, 'sleep_awake_duration': 6, 'duration': 441, 'max_hr': 80, 'awake_count': 2, 'avg_spo2': 98, 'min_spo2': 95, 'wake_up_time': 1767509700}]
Name: segment_details, dtype: object

,avg_hr,bedtime,max_spo2,min_hr,sleep_rem_duration,timezone,sleep_light_duration,sleep_deep_duration,sleep_awake_duration,duration,max_hr,awake_count,avg_spo2,min_spo2,wake_up_time
0,49,1767482880,99,41,102,4,225,114,6,441,80,2,98,95,1767509700

In [8]:

# TODO - add Uid, Key and Time for every row
all_sleep_data = df.Value[(df.Key == 'sleep') & (df.Tag == 'daily_report')]

Parse JSONs of `sleep` into a new DF
`Uid`, `Key`, `Time`, `avg_spo2` ...

In [9]:
all_sleep_data_json = json.loads('[' + ','.join(all_sleep_data) + ']')
all_sleep_data_df = pd.json_normalize(data=all_sleep_data_json, max_level=2)
all_sleep_data_df

,total_duration,sleep_rem_duration,sleep_nap_duration,total_turn_over,avg_hr,avg_spo2,sleep_light_duration,total_long_duration,sleep_score,day_sleep_evaluation,...,total_body_move,awake_count,max_hr,total_snore_disturb,segment_details,sleep_deep_duration,min_hr,min_spo2,max_spo2,sleep_algorithm_version
0,428,125,0,0,56,0,167,428,70,0,...,0,2,80,0,"[{'awake_count': 2, 'wake_up_time': 1736930100, 'duration': 428, 'sleep_deep_duration': 136, 'timezone': 4, 'bedtime': 1736902380, 'min_hr': 48, 'max_hr': 80, 'sleep_awake_duration': 34, 'sleep_rem_duration': 125, 'avg_hr': 56, 'sleep_light_duration': 167}]",136,48,NaN,NaN,NaN
1,515,119,65,0,54,0,226,450,77,0,...,0,1,79,0,"[{'awake_count': 1, 'sleep_light_duration': 226, 'sleep_rem_duration': 119, 'bedtime': 1736985060, 'sleep_deep_duration': 105, 'wake_up_time': 1737012900, 'sleep_awake_duration': 14, 'max_hr': 65, 'min_hr': 43, 'duration': 450, 'timezone': 4, 'avg_hr': 50}, {'sleep_light_duration': 0, 'bedtime': 1737018240, 'max_hr': 79, 'awake_count': 0, 'wake_up_time': 1737022140, 'sleep_rem_duration': 0, 'avg_hr': 58, 'min_hr': 53, 'sleep_deep_duration': 0, 'duration': 65, 'sleep_awake_duration': 0, 'timezone': 4}]",105,43,NaN,NaN,NaN
2,496,121,0,0,57,0,247,496,86,0,...,0,2,99,0,"[{'sleep_rem_duration': 121, 'wake_up_time': 1737100800, 'duration': 496, 'bedtime': 1737070020, 'max_hr': 99, 'sleep_deep_duration': 128, 'avg_hr': 57, 'sleep_light_duration': 247, 'min_hr': 47, 'sleep_awake_duration': 17, 'timezone': 4, 'awake_count': 2}]",128,47,NaN,NaN,NaN
3,523,121,0,0,50,0,246,523,93,0,...,0,0,79,0,"[{'duration': 523, 'sleep_light_duration': 246, 'sleep_deep_duration': 156, 'sleep_rem_duration': 121, 'min_hr': 43, 'timezone': 4, 'avg_hr': 50, 'bedtime': 1737154020, 'wake_up_time': 1737185400, 'sleep_awake_duration': 0, 'awake_count': 0, 'max_hr': 79}]",156,43,NaN,NaN,NaN
4,432,108,0,0,50,0,172,432,83,0,...,0,1,61,0,"[{'timezone': 4, 'sleep_awake_duration': 4, 'awake_count': 1, 'wake_up_time': 1737271800, 'max_hr': 61, 'duration': 432, 'min_hr': 40, 'sleep_deep_duration': 152, 'sleep_rem_duration': 108, 'avg_hr': 50, 'bedtime': 1737245640, 'sleep_light_duration': 172}]",152,40,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,1087,155,469,0,59,97,259,805,78,1,...,0,3,96,0,"[{'max_hr': 96, 'avg_hr': 53, 'min_spo2': 94, 'bedtime': 1767130560, 'sleep_light_duration': 259, 'sleep_deep_duration': 204, 'min_hr': 46, 'sleep_rem_duration': 155, 'sleep_awake_duration': 12, 'awake_count': 3, 'max_spo2': 99, 'avg_spo2': 97, 'wake_up_time': 1767168360, 'timezone': 4, 'duration': 618}, {'max_hr': 67, 'avg_hr': 61, 'min_spo2': 95, 'bedtime': 1767174060, 'sleep_light_duration': 0, 'sleep_deep_duration': 0, 'min_hr': 57, 'sleep_rem_duration': 0, 'sleep_awake_duration': 0, 'awake_count': 0, 'max_spo2': 95, 'avg_spo2': 95, 'wake_up_time': 1767177060, 'timezone': 4, 'duration': 187}, {'max_hr': 85, 'avg_hr': 62, 'min_spo2': 95, 'bedtime': 1767178260, 'sleep_light_duration': 0, 'sleep_deep_duration': 0, 'min_hr': 56, 'sleep_rem_duration': 0, 'sleep_awake_duration': 0, 'awake_count': 0, 'max_spo2': 99, 'avg_spo2': 97, 'wake_up_time': 1767186480, 'timezone': 4, 'duration': 137}, {'max_hr': 78, 'avg_hr': 61, 'min_spo2': 94, 'bedtime': 1767195780, 'sleep_light_duration': 0, 'sleep_deep_duration': 0, 'min_hr': 56, 'sleep_rem_duration': 0, 'sleep_awake_duration': 0, 'awake_count': 0, 'max_spo2': 99, 'avg_spo2': 97, 'wake_up_time': 1767204480, 'timezone': 4, 'duration': 145}]",204,46,94.0,99.0,0.0
159,572,97,62,0,55,97,236,510,80,0,...,0,1,81,0,"[{'sleep_rem_duration': 97, 'duration': 510, 'max_spo2': 99, 'bedtime': 1767225060, 'max_hr': 81, 'avg_hr': 51, 'awake_count': 1, 'min_spo2': 94, 'avg_spo2': 97, 'sleep_deep_duration': 177, 'wake_up_time': 1767256200, 'min_hr': 44, 'sleep_light_duration': 236, 'sleep_awake_duration': 9, 'timezone': 4}, {'sleep_rem_duration': 0, 'duration': 62, 'max_spo2': 97, 'bedtime': 1767264660, 'max_hr': 76, 'avg_hr': 58, 'awake_count': 0, 'min_spo2': 94, 'avg_spo2': 96, 'sleep_deep_duration': 0, 'wake_up_time': 1767268380, 'min_hr': 53, 'sleep_light_duration': 0, 'sleep_awake_duration': 0, 'timezone': 4}]",177,44,94.0,99.0,0.0
160,518,131,36,0,57,97,214,482,91,0,...,0,0,78,0,"[{'avg_spo2': 97, 'sleep_light_duration': 214, 'wake_up_time': 1767339300, 'awake_count': 0, 'sleep_awake_duration': 0, 'timezone': 4, 'min_hr': 42, 'duration': 482, 'min_spo2': 94, 'max_hr': 78, 'avg_hr': 50, 'max_spo2': 99, 'bedtime': 1767310380, 'sleep_deep_duration': 137, 'sleep_rem_duration': 131}, {'avg_spo2': 96, 'sleep_light_duration': 0, 'wake_up_time': 1767347040, 'awake_count': 0, 'sleep_awake_duration': 0, 'timezone': 4, 'min_hr': 60, 'duration': 36, 'min_spo2': 96, 'max_hr': 77, 'avg_hr': 64, 'max_spo2': 96, 'bedtime': 1767344880, 'sleep_deep_duration': 0, 'sleep_rem_duration': 0}]",137,42,94.0,99.0,0.0
161,439,119,0,0,53,97,172,439,70,0,...,0,4,82,0,"[{'min_spo2': 93, 'sleep_rem_duration': 119, 'min_hr': 44, 'awake_count': 4, 'sleep_light_duration': 172, 'duration': 439, 'wake_up_time': 1767426900, 'sleep_deep_duration': 148, 'avg_hr': 53, 'avg_spo2': 97, 'bedtime': 1767399600, 'max_spo2': 99, 'timezone': 4, 'sleep_awake_duration': 16, 'max_hr': 82}]",148,44,93.0,99.0,0.0
162,441,102,0,0,49,98,225,441,80,0,...,0,2,80,0,"[{'avg_hr': 49, 'bedtime': 1767482880, 'max_spo2': 99, 'min_hr': 41, 'sleep_rem_duration': 102, 'timezone': 4, 'sleep_light_duration': 225, 'sleep_deep_duration': 114, 'sleep_awake_duration': 6, 'duration': 441, 'max_hr': 80, 'awake_count': 2, 'avg_spo2': 98, 'min_spo2': 95, 'wake_up_time': 1767509700}]",114,41,95.0,99.0,0.0

In [10]:
#df.Value[(df.Time == 1767484800)]