In [1]:
import pandas as pd
import json

In [2]:
file_path = '../data/miband/20260406_8278074507_MiFitness_ams1_data_copy/20260406_8278074507_MiFitness_hlth_center_aggregated_fitness_data.csv'
df_raw = pd.read_csv(file_path)

In [6]:
df_steps = df_raw[(df_raw['Key'] == 'steps') & (df_raw['Tag'] == 'daily_report')].copy()

steps_data_list = [json.loads(val) for val in df_steps['Value']]
df_steps_normalized = pd.json_normalize(steps_data_list)

df_steps_result = df_steps[['Uid', 'Sid', 'Time']].reset_index(drop=True).join(df_steps_normalized)

df_steps_result

            Uid      Sid        Time  calories   goal  distance  steps
0    8278074507  default  1736812800       410   6000      6298   9910
1    8278074507  default  1736899200       620   6000      5575  10832
2    8278074507  default  1736985600        91   6000      2223   3290
3    8278074507  default  1737072000        13   6000       177    262
4    8278074507  default  1737331200        14   6000       140    206
..          ...      ...         ...       ...    ...       ...    ...
292  8278074507  default  1775088000        90  10000      2079   2845
293  8278074507  default  1775174400        75  10000      1616   2354
294  8278074507  default  1775260800       104  10000      2633   3645
295  8278074507  default  1775347200       181  10000      4698   6311
296  8278074507  default  1775433600        22  10000       163    241

[297 rows x 7 columns]

In [7]:
df_steps_result['Time'] = pd.to_datetime(df_steps_result['Time'], unit='s')

df_steps_result

            Uid      Sid       Time  calories   goal  distance  steps
0    8278074507  default 2025-01-14       410   6000      6298   9910
1    8278074507  default 2025-01-15       620   6000      5575  10832
2    8278074507  default 2025-01-16        91   6000      2223   3290
3    8278074507  default 2025-01-17        13   6000       177    262
4    8278074507  default 2025-01-20        14   6000       140    206
..          ...      ...        ...       ...    ...       ...    ...
292  8278074507  default 2026-04-02        90  10000      2079   2845
293  8278074507  default 2026-04-03        75  10000      1616   2354
294  8278074507  default 2026-04-04       104  10000      2633   3645
295  8278074507  default 2026-04-05       181  10000      4698   6311
296  8278074507  default 2026-04-06        22  10000       163    241

[297 rows x 7 columns]

In [8]:
import os

output_dir = '../data/processed_data'
output_path = os.path.join(output_dir, 'miband_steps_processed.csv')
df_steps_result.to_csv(output_path, index=False)